name: Upload Python Package to PyPI
on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Setup Poetry
      uses: abatilo/actions-poetry@v3.0.1
    - name: Build
      run: poetry build
    - name: Publish to PyPI
      run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}