name: Upload Python Package to TestPyPI
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Setup Poetry
      uses: abatilo/actions-poetry@v3.0.1
    - name: Configure Poetry for TestPyPI
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config http-basic.testpypi __token__ ${{ secrets.TESTPYPI_API_TOKEN }}
    - name: Build
      run: poetry build
    - name: Publish to TestPyPI
      run: poetry publish -r testpypi